### ISSUE TITLE
jxmlease is required for fetch, but not listed in docs

### ISSUE THREAD

**Issue by cidrblock** [ansible-collections/community.yang#18]
I'm also curious if we should switch to xmltodict across the board here if we are going to use that elsewhere.

```
- hosts: nxos101:eos101
  gather_facts: False
  tasks:
  - name: Fetch list of supported yang model names
    community.yang.fetch:
    register: available
```
```
fatal: [nxos101]: FAILED! => {"changed": false, "msg": "jxmlease is required to store response in json format but does not appear to be installed. It can be installed using `pip install jxmlease`"}
```
