### ISSUE TITLE
Getting all with fetch fails on dependant models

### ISSUE THREAD

**Issue by cidrblock** [ansible-collections/community.yang#23]
I think this may be an issue with the quotes when regexing the import statements.

```
def get_schema_and_dependants(self, schema_id, result):
        try:
            found, data_model = self.get_one_schema(schema_id, result)
        except ValueError as exc:
            raise ValueError(exc)

        if found:
            result["fetched"][schema_id] = data_model
            importre = re.compile(r"import (.+) {")
            all_found = importre.findall(data_model)
            all_found = [re.sub("['\"]", "", imp) for imp in all_found]
            return all_found
```

^^^ fixed the issue

example of issue
```
 - community.yang.fetch:
      name: ietf-yang-types
    
  - community.yang.fetch:
      name: openconfig-network-instance
```

```
Fetched 'arista-mpls-augments' yang model
"openconfig-network-instance"
fatal: [eos101]: FAILED! => {
    "changed": false,
    "msg": "Fail to fetch '\"openconfig-network-instance\"' yang model"
}
```
