### ISSUE TITLE
[Proposal ]Generic Ansible modules for configuring YANG and NETCONF enabled devices using structured data (JSON/YAML)

### ISSUE THREAD

**Issue by ganeshrn** [ansible-collections/community.yang#3]
# Proposal: <proposal name>
Generic Ansible modules for configuring YANG and Netconf enabled devices using structured data (JSON/YAML)
*Author*: Ganesh B. Nalawade @ganeshrn

*Date*: 2018/04/18

- Status: New
- Proposal type: community.yang design
- Targeted Release: 1.0.0
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: 4 weeks

## Motivation
Describe the reasons for this proposal.
Provide a generic to configure network devices using structured data in the form of JSON/YAML that uses the data model defined by YANG. 
Handcrafting XML configuration payload by referring YANG model supported by the remote host is not easy. The plugins in the ``community.yang`` collection will be designed to maximize flexibility (YANG variant independent) and provide a simple to use approach. 

### Problems
What problems exist that this proposal will solve?

1. As a user, I want to configure a YANG and Netconf enabled device using structured data (JSON/YAML) instead of vendor-specific CLI commands.
2. As a user, I want to have reference to the structured data skeleton supported by the device to avoid handcrafting it by directly referring to YANG model.
3. As a user, I want to fetch the running-configuration on the remote host for the given YANG resource and render it in structured (JSON/YAML) format.
4.  As a user, I want to push the structured configuration data which is either generated by filling in the configuration values in the structured skeleton created by [2] or by modifying the structured data fetched in [3]  to any Netconf enabled remote device.

## Solution proposal
Abstract all the YANG related complexities from the user with the help of Ansible modules and plugins as follows.

### **`community.yang.fetch` module:**
The module fetches the given Yang model and all it's dependent model from the device and returns it as the result of the task along with the number of yang models fetched. 
Module description:

DOCUMENTATION:
```
---
module: fetch
short_description: Fetch given yang model and it's dependencies
description:
    - Fetch given yang model and its dependant yang model from device using netconf rpc.
options:
  name:
    description:
      - Name of the yang model to fetched from remote host. This will also fetch all
        the dependent yang models and return as part of result. If the value is set
        to I(all) in that case all the yang models supported by remote host will be
        fetched.
  dir:
    description:
      - This is an optional argument which provide the directory path in which the fetched
        yang modules will be saved. The name of the file is same as that of the yang module
        name prefixed with `.yang` extension.
```

RETURN:
```
number_schema_fetched:
  description: Total number of yang model fetched from remote host
  returned: always apart from low-level errors (such as action plugin)
  type: int
  sample: 10
fetched:
  description: This is a key-value pair were key is the name of the yang model and value
               is the yang model itself in string format
  returned: always apart from low-level errors (such as action plugin)
  type: dict
  sample: {"ietf-inet-types": "module ietf-inet-types ...<--snip-->"}
```

EXAMPLES:
```
- name: Fetch given yang model from remote host
  community.yang.fetch:
    name: "{{ item }}"
  loop:
    - openconfig-interface
    - openconfig-bgp

- name: Fetch list of supported yang model names
  community.yang.fetch:

- name: Fetch all the yang models supported by remote host and store it in dir location
  community.yang.fetch:
    name: all
    dir: "{{ playbook_dir }}/yang_files"
```

### **`community.yang.generate_spec` module:**
The module will be read the given Yang model and generate the corresponding JSON, XML
schema and the YANG tree representation (as per [RFC 8340](https://tools.ietf.org/html/rfc8340)) of the model and return in the result and optionally store it in this individual files on the control node.
Module description:

DOCUMENTATION:
```
module: generate_spec
short_description: Generate JSON/XML schema and tree representation for given YANG model
description:
    - The module will be read the given Yang model and generate the corresponding JSON, XML
      schema and the YANG tree representation (as per RFC 8340) of the model and return in the
      result and optionally store it in this individual files on control node.
options:
  content:
    description:
      - The text content of the top level YANG model for the the should be generated.
        This option is mutually-exclusive with C(path) option.
    type: str
  file:
    description:
      - The file path of the top level YANG model for the spec should be generated.
        This option is mutually-exclusive with C(content) option.
    type: str
  search_path:
    description:
      - is a colon C(:) separated list of directories to search for imported yang modules
        in the yang file mentioned in C(path) option. If the value is not given it will search in
        the default directory path.
    type: path
    default: "~/.ansible/yang/spec"
  doctype:
    description:
      - Identifies the root node of the configuration skeleton. If value is C(config) only configuration
        data will be present in skeleton, if value is C(data) both config and state data fields will be present
        in output.
    default: config
    choices: ['config', 'data']
  json_schema:
    description: The options to control the way JSON schema is generated
    type: dict
    suboptions:
      path:
        description: The file path to which the generated JSON schema should be stored.
        type: path
      defaults:
        description:
          - This boolean flag indicates if the generated JSON configuration schema should have
            fields initialized with default values or not.
        type: bool
        default: False
  xml_schema:
    description: The options to control the way XML schema is generated
    type: dict
    suboptions:
      path:
        description: The file path to which the generated XML schema should be stored.
        type: path
      defaults:
        description:
          - This boolean flag indicates if the generated XML configuration schema should have
            fields initialized with default values or not.
        type: bool
        default: False
      annotations:
        description:
          - The boolean flag identifies if the XML skeleton should have comments describing the field or not.
        default: False
        type: bool
  tree_schema:
    description: The options to control the way tree schema is generated
    type: dict
    suboptions:
      path:
        description: The file path to which the generated tree schema should be stored.
        type: path
```
RETURN :
```
tree_schema:
  description: The tree schema representation of yang scehma as per RFC 8340
  returned: always
  type: dict
  sample: |
    module: openconfig-interfaces
      +--rw interfaces
         +--rw interface* [name]
            +--rw name             -> ../config/name
            +--rw config
            |  +--rw name?            string
            |  +--rw type             identityref
            |  +--rw mtu?             uint16
            |  +--rw loopback-mode?   boolean
            |  +--rw description?     string
            |  +--rw enabled?         boolean
            +--ro state
            |  +--ro name?            string
            |  +--ro type             identityref
            |  +--ro mtu?             uint16
            |  +--ro loopback-mode?   boolean
            |  +--ro description?     string
            |  +--ro enabled?         boolean
            |  +--ro ifindex?         uint32
            |  +--ro admin-status     enumeration
            |  +--ro oper-status      enumeration
            |  +--ro last-change?     oc-types:timeticks64
json_schema:
  description: The json schema generated from yang document
  returned: always
  type: dict
  sample: |
    {
        "openconfig-interfaces:interfaces": {
            "interface": [
                {
                    "hold-time": {
                        "config": {
                            "down": "",
                            "up": ""
                        }
                    },
                    "config": {
                        "description": "",
                        "type": "",
                        "enabled": "",
                        "mtu": "",
                        "loopback-mode": "",
                        "name": ""
                    },
                    "name": "",
                    "subinterfaces": {
                        "subinterface": [
                            {
                                "index": "",
                                "config": {
                                    "index": "",
                                    "enabled": "",
                                    "description": ""
                                }
                            }
                        ]
                    }
                }
            ]
        }
xml_schema:
  description: The xml configuration schema generated from yang document
  returned: always
  type: dict
  sample: |
    <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <interfaces xmlns="http://openconfig.net/yang/interfaces">
        <interface>
          <name/>
          <config>
            <name/>
            <type/>
            <mtu/>
            <loopback-mode></loopback-mode>
            <description/>
            <enabled>True</enabled>
          </config>
          <hold-time>
            <config>
              <up></up>
              <down></down>
            </config>
          </hold-time>
          <subinterfaces>
            <subinterface>
              <index/>
              <config>
                <index></index>
                <description/>
                <enabled></enabled>
              </config>
            </subinterface>
          </subinterfaces>
        </interface>
      </interfaces>
    </config>
```
EXAMPLES:
```
- name: generate spec from openconfig interface data and in result
  community.yang.generate_spec:
    file: "openconfig/public/release/models/interfaces/openconfig-interfaces.yang"
    search_path: "{{ playbook_dir }}/openconfig/public/release/models:pyang/modules"

- name: generate spec from openconfig interface config data and store it in file
  community.yang.generate_spec:
    file: "openconfig/public/release/models/interfaces/openconfig-interfaces.yang"
    search_path: "{{ playbook_dir }}/openconfig/public/release/models:pyang/modules"
    doctype: config
    json_schema:
      path: "~/.ansible/yang/spec/{{ inventory_hostname }}/openconfig-interfaces-config.json"
      defaults: True
    xml_schema:
      path: "~/.ansible/yang/spec/{{ inventory_hostname }}/openconfig-interfaces-config.xml"
      defaults: True
      annotations: True
    tree_schema:
      path: "~/.ansible/yang/spec/{{ inventory_hostname }}/openconfig-interfaces-config.tree"
```

### **`community.yang.get` module:**
The module will fetch the configuration data for a given YANG model and render it in JSON format (as per [RFC 7951](https://tools.ietf.org/html/rfc7951)).
Module description:

DOCUMENTATION:
```
---
module: get
short_description: Fetch the device configuration and render it in JSON format defined by RFC7951
description:
    - The module will fetch the configuration data for a given YANG model and render it in
      JSON format (as per RFC 7951).
options:
  filter:
    description:
    - This argument specifies the XML string which acts as a filter to restrict the
      portions of the data to be are retrieved from the remote device. If this option
      is not specified entire configuration or state data is returned in result depending
      on the value of C(source) option. The C(filter) value can be either XML string
      or XPath, if the filter is in XPath format the NETCONF server running on remote
      host should support xpath capability else it will result in an error.
    type: str
  source:
    description:
    - This argument specifies the datastore from which configuration data should be
      fetched. Valid values are I(running), I(candidate) and I(startup). If the C(source)
      value is not set both configuration and state information are returned in response
      from running datastore.
    type: str
    choices:
    - running
    - candidate
    - startup
  lock:
    description:
    - Instructs the module to explicitly lock the datastore specified as C(source).
      If no I(source) is defined, the I(running) datastore will be locked. By setting
      the option value I(always) is will explicitly lock the datastore mentioned in
      C(source) option. By setting the option value I(never) it will not lock the
      C(source) datastore. The value I(if-supported) allows better interworking with
      NETCONF servers, which do not support the (un)lock operation for all supported
      datastores.
    type: str
    default: never
    choices:
    - never
    - always
    - if-supported
  file:
    description:
      - The file path of the YANG model that corresponds to the configuration fetch from the remote host.
        This options accepts wildcard (*) as well for the filename in case the configuration requires
        to parse multiple yang file. For example "openconfig/public/tree/master/release/models/interfaces/*.yang"
  search_path:
    description:
      - is a colon C(:) separated list of directories to search for imported yang modules
        in the yang file mentioned in C(path) option. If the value is not given it will search in
        the default directory path.
    type: path
    default: "~/.ansible/yang/spec"
```

RETURN:
```
json_data:
  description: The running configuration in json format
  returned: always
  type: dict
  sample: |
    {
        "openconfig-interfaces:interfaces":
         {
            "interface": [{
                "name" : "GigabitEthernet0/0/0/2",
                "config" : {
                    "name" : "GigabitEthernet0/0/0/2",
                    "description": "configured by Ansible yang collection",
                    "mtu": 1024
                }
            }]
         }
    }
xml_data:
  description: The running configuration in xml format
  returned: always
  type: str
  sample: |
     <data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\">
       <interface-configurations xmlns=\"http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg\">
         <interface-configuration>
             <active>act</active>
             <interface-name>GigabitEthernet0/0/0/2</interface-name>
             <description>configured by Ansible yang collection</description>
             <mtu>1024</mtu>
         </interface-configuration>
       </interface-configurations>
     </data>
```
EXAMPLES:
```
- name: fetch interface configuration and return it in JSON format
  community.yang.get:
    filter: |
        <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"><interface-configuration>
        </interface-configuration></interface-configurations>
    file: "{{ playbook_dir }}/YangModels/yang/tree/master/vendor/cisco/xr/613/*.yang"
    search_path: "{{ playbook_dir }}/YangModels/yang/tree/master/vendor/cisco/xr/613:{{ playbook_dir }}/pyang/modules"
```

### **`community.yang.configure` module:**
The module takes the JSON configuration as input. Pre-validates the config with the corresponding YANG model and converts input JSON configuration to XML payload to be pushed on the remote host using netconf connection.

Module description:

DOCUMENTATION:
```
---
module: configure
short_description: Reads the input configuration in JSON format and pushes to the remote host over netconf
description:
    - The module takes the JSON configuration as input.
    - Pre-validates the config with the corresponding YANG model.
    - Converts input JSON configuration to XML payload to be pushed on the remote host
      using netconf connection.
options:
  config:
    description:
      - The running-configuration to be pushed onto the device in JSON format (as per RFC 7951).
    type: str
    required: True
  get_filter:
    description:
      - The filter in xml string format to fetch a subset of the running-configuration for the YANG model
        given in C(file) option. If this option is provided it will compare the current running-configuration
        on the device with what is provided in the C(config) option and push to C(config) value to device only
        if it is different to ensure idempotent task run.
    type: str
  file:
    description:
      - The file path of the YANG model that corresponds to the configuration fetch from the remote host.
        This options accepts wildcard (*) as well for the filename in case the configuration requires
        to parse multiple yang file. For example "openconfig/public/tree/master/release/models/interfaces/*.yang"
  search_path:
    description:
      - is a colon C(:) separated list of directories to search for imported yang modules
        in the yang file mentioned in C(path) option. If the value is not given it will search in
        the default directory path.
    type: path
    default: "~/.ansible/yang/spec"
```

RETURN:
```
diff:
  description: If --diff option in enabled while running, the before and after configuration change are
               returned as part of before and after key.
  returned: when diff is enabled
  type: dict
  sample:
    "after": "<rpc-reply>\n<data>\n<configuration>\n<version>17.3R1.10</version>...<--snip-->"
    "before": "<rpc-reply>\n<data>\n<configuration>\n <version>17.3R1.10</version>...<--snip-->"
```

EXAMPLES:
```
- name: configure interface using structured data in JSON format
  community.yang.configure:
    config: {
            "openconfig-interfaces:interfaces":
             {
                "interface": [{
                    "name" : "GigabitEthernet0/0/0/2",
                    "config" : {
                        "name" : "GigabitEthernet0/0/0/2",
                        "enabled": true,
                        "description": "configured by Ansible yang role",
                        "mtu": 1024
                    }
                }]
             }
        }
    get_filter: |
        <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"><interface-configuration>
        </interface-configuration></interface-configurations>
    file: "{{ playbook_dir }}/public/release/models/interfaces/openconfig-interfaces.yang"
    search_path: "{{ playbook_dir }}/public/release/models"
```

## Testing
* Add integration and unit test for `community.yang.fetch` module. 
* Add integration and unit test for `community.yang.generate_spec` module. 
* Add integration and unit test for `community.yang.get` module. 
* Add integration and unit test for `community.yang.configure` module. 

## Documentation
* Add module documentation for newly added plugins
