### ISSUE TITLE
Add module generate_argument_spec

### ISSUE THREAD

**Issue by jgroom33** [ansible-collections/community.yang#65]
##### SUMMARY
The current steps for developing a netconf ansible module in a collection is:
1. Use [resource_module_builder](https://github.com/ansible-network/resource_module_builder)
2. Choose YANG
3. Examine/parse YANG
4. Write json based [argument_spec](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec) from selective YANG components
5. Run resource_module_builder to generate module

NOTE: Steps 3-4 are currently simplified using `community.yang.generate_spec` and a schema generator

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- community.yang.generate_argument_spec

##### ADDITIONAL INFORMATION

This would automate the step of generating the necessary argument_spec (Steps 3-4 above)

```yaml
    - name: Generate argument_spec for foo yang
      community.yang.generate_argument_spec:
        file: foo.yang
        output:
          path: "schemas/foo.yang.json"
```
